FROM alpine:latest
LABEL version="1.0.0" os="linux" distro="alpine" maintainer="juan pablo aguirre"
RUN adduser jaguirre --disabled-password && mkdir "/home/jaguirre/receipts"
CMD ping google.com

# docker build . -t hello-alpine:1.0.0
# docker build . -t jaguirrema/hello-alpine:1.0.0
# docker login
# docker push jaguirrema/hello-alpine:1.0.0
# docker run --name hello-alpine hello-alpine:1.0.0


