version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    - MONGO_INITDB_DATABASE=auth
    networks:
      - mongo-express-network
  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    networks:
      - mongo-express-network
networks:
  mongo-express-network:
    driver: bridge
